apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w9x6m83p4-python
  janus-idp.io/tekton: w9x6m83p4-python
  backstage.io/kubernetes-id: w9x6m83p4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w9x6m83p4-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
